name: pickaxe-env
channels:
 - conda-forge
dependencies:
 - black
 - black-jupyter
 - conda-build
 - flake8
 - flake8-bugbear
 - flake8-docstrings
 - ipython
 - isort
 - jupyter
 - memory_profiler
 - mordred
 - mypy
 - numpy
 - numpydoc
 - pandas
 - pillow
 - pymongo
 - pylint
 - pytest
 - pytest-cov
 - python>=3.9
 - rdkit
 - safety
 - scikit-learn
 - scipy
 - snakeviz
 - sphinxcontrib-napoleon
 - sqlalchemy
 - tox