[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = 'doranet'
version = '0.4.1+build.1'
authors = [
    { name='William Sprague', email='wsprague@u.northwestern.edu' },
    { name='Quan Zhang', email='quanzhang@northwestern.edu' },
]
description = 'Python package for generating and analyzing chemical reaction networks'
readme = 'README.md'
requires-python = '>=3.10'
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Development Status :: 2 - Pre-Alpha",
]
license = {file = "LICENSE"}
dependencies = [
    "ipython",
    "numpy",
    "pandas",
    "pillow",
    "pyarrow",
    "rdkit",
    "scipy",
]

[project.urls]
Homepage = "https://github.com/wsprague-nu/doranet"
Issues = "https://github.com/wsprague-nu/doranet/issues"

[[tool.mypy.overrides]]
module = [
    "rdkit.*",
    "PIL.*",
    "IPython.*"
]
ignore_missing_imports = true

[tool.ruff]
line-length = 80

[tool.ruff.format]
quote-style = "double"
line-ending = "lf"
indent-style = "space"

[tool.ruff.lint]
select = ["E", "F", "B", "I", "SIM"]
